# This is a WIP to deploy infrastructure automatically
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - dir
  build:
    commands:
      - python --version
#      - pip3 show
      - conda
