# This is a WIP to deploy infrastructure automatically
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - tests/setup_test_env.sh
  build:
    commands:
      - tests/run_all.sh
